apiVersion: kumquat.guidewire.com/v1beta1
kind: Template
metadata:
  name: multi-yaml
  namespace: templates
spec:
  query: | #sql
    SELECT crd.data AS crd
    FROM "CustomResourceDefinition.apiextensions.k8s.io" AS crd
    WHERE crd.name LIKE "%.aws.upbound.io"
  template:
    language: cue
    batchModeProcessing: true
    fileName: |
      ./output/out.yaml
    data: | #cue
      _unique_groups_map: {
        for result in DATA {
          "\(result.crd.spec.group)": result.crd.spec.group
        }
      }
      _unique_groups: [ for g in _unique_groups_map {g}]
      _role_name: "kumquat-sample-role"
      
      [
        {
          apiVersion: "rbac.authorization.k8s.io/v1"
          kind: "ClusterRole"
          metadata: {
            name: _role_name
          }
          rules: [
            {
              apiGroups: _unique_groups
              resources: [
                  "*"
              ]
              verbs: ["get", "list", "watch"]
            }
          ]
        },
        {
          apiVersion: "rbac.authorization.k8s.io/v1"
          kind: "ClusterRoleBinding"
          metadata: {
            name: "\(_role_name)-binding"
          }
          subjects: [
            {
              kind: "ServiceAccount"
              name: "default"
              namespace: "default"
            }
          ]
          roleRef: {
            apiGroup: "rbac.authorization.k8s.io"
            kind: "ClusterRole"
            name: _role_name
          }
        }
      ]
