apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kumquat.fullname" . }}-manager-role
  labels:
  {{- include "kumquat.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kumquat.guidewire.com
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kumquat.guidewire.com
  resources:
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - kumquat.guidewire.com
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kumquat.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kumquat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kumquat.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kumquat.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
