apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kumquat.fullname" . }}-template-viewer-role
  labels:
  {{- include "kumquat.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kumquat.guidewire.com
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kumquat.guidewire.com
  resources:
  - templates/status
  verbs:
  - get
