name: Publish to GHCR

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install yq
        uses: mikefarah/yq@master

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GHCR for Helm
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Package and push Helm chart
        run: |
          # Extract version from git tag
          VERSION=${GITHUB_REF#refs/tags/v}
                                                      yq eval ".version = \"${VERSION}\"" -i charts/kumquat/Chart.yaml
          yq eval ".appVersion = \"${VERSION}\"" -i charts/kumquat/Chart.yaml
          
          # Package and push c          # Packel          # Package and push c          # sh kumquat-${VERSION}.tgz oci://${{ env.REGISTRY }}/${{ github.repository }}/charts
